spring:
  datasource:
    username: admin
    password: admin
    #?serverTimezone=UTC解决时区的报错
    #要设置亚洲时间serverTimezone=Asia/Shanghai
    url: jdbc:mysql://47.96.234.116:3306/conference?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    #更改上传文件大小限制
  servlet:
    multipart:
      max-file-size: 100MB # 单个文件大小
      max-request-size: 100MB # 设置总上传的数据大小
      enabled: true #开启
  #
  mvc:
    hiddenmethod:
      filter:
        enabled: true

#整合mybatis
mybatis:
  type-aliases-package: com.conference.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true




