spring:
  datasource:
    username: admin
    password: admin
    #?serverTimezone=UTC解决时区的报错
    url: jdbc:mysql://47.96.234.116:3306/conference?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

#整合mybatis
mybatis:
  type-aliases-package: com.conference.entity
  mapper-locations: classpath:mybatis/dao/*.xml
  configuration:
    map-underscore-to-camel-case: true

